// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PMS.PatientAPI.Models;

namespace PMS.PatientAPI.Migrations
{
    [DbContext(typeof(PatientDbContext))]
    partial class PatientDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PMS.PatientAPI.Models.AllergyModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AllergyId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Allergy_Clinical_Information")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Allergy_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Allergy_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Allergy_Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Allergies");
                });

            modelBuilder.Entity("PMS.PatientAPI.Models.DiagnosisModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Diagnosis_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diagnosis_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Diagnosis_Is_Depricated")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Diagnosis");
                });

            modelBuilder.Entity("PMS.PatientAPI.Models.DrugsModel", b =>
                {
                    b.Property<int>("DrugID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Drug_Form")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Drug_Generic_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Drug_Manufacture_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Drug_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Drug_Strength")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DrugID");

                    b.ToTable("Drugs");
                });

            modelBuilder.Entity("PMS.PatientAPI.Models.PatientAllergyDetailsModel", b =>
                {
                    b.Property<int>("PatientAllergyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AllergyId")
                        .HasColumnType("int");

                    b.Property<string>("Allergy_Clinical")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Allergy_Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Allergy_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Allergy_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("Is_Allergy_Fatal")
                        .HasColumnType("bit");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("PatientAllergyId");

                    b.ToTable("PatientAllergies");
                });

            modelBuilder.Entity("PMS.PatientAPI.Models.PatientDemographicDetailsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<long>("ContactNo")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DOB")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ethnicity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LanguagesKnow")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Race")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("PatientDemographics");
                });

            modelBuilder.Entity("PMS.PatientAPI.Models.PatientEmergencyContactModel", b =>
                {
                    b.Property<int>("EmergencyContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ContactNo")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAllowed")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Relationship")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("EmergencyContactId");

                    b.ToTable("PatientEmergencyContacts");
                });

            modelBuilder.Entity("PMS.PatientAPI.Models.PatientVisitDiagnosisModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Diagnosis_Code")
                        .HasColumnType("int");

                    b.Property<bool>("Diagnosis_Is_Depricated")
                        .HasColumnType("bit");

                    b.Property<int>("Patient_Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Visit_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PatientVisitDiagnosis");
                });

            modelBuilder.Entity("PMS.PatientAPI.Models.PatientVisitMedicationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Drug_BrandName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Drug_Form")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Drug_GenericName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Drug_Id")
                        .HasColumnType("int");

                    b.Property<string>("Drug_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Patient_Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VisitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PatientVisitMedications");
                });

            modelBuilder.Entity("PMS.PatientAPI.Models.PatientVisitProceduresModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Diagnosis_Is_Depricated")
                        .HasColumnType("bit");

                    b.Property<int>("Patient_Id")
                        .HasColumnType("int");

                    b.Property<int>("Procedure_Code")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VisitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PatientVisitProcedures");
                });

            modelBuilder.Entity("PMS.PatientAPI.Models.PatientVisitVitalsModel", b =>
                {
                    b.Property<int>("VisitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Blood_Pressure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Body_Temperature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Height")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Patient_Id")
                        .HasColumnType("int");

                    b.Property<string>("Respiration_Rate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Visit_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Weight")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VisitId");

                    b.ToTable("PatientVisitVitals");
                });

            modelBuilder.Entity("PMS.PatientAPI.Models.Patient_Diagnosis_MedicationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diagnosis_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diagnosis_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Diagnosis_Is_Depricated")
                        .HasColumnType("bit");

                    b.Property<string>("Drug_Form")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Drug_GenericName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Drug_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Drug_Strength")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Procedure_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Procedure_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Procedure_Is_Depricated")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VisitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VisitId");

                    b.ToTable("Patient_Diagnosis_Medication");
                });

            modelBuilder.Entity("PMS.PatientAPI.Models.ProceduresModel", b =>
                {
                    b.Property<int>("ProcedureID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Procedure_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Procedure_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Procedure_Is_Depricated")
                        .HasColumnType("bit");

                    b.HasKey("ProcedureID");

                    b.ToTable("Procedures");
                });

            modelBuilder.Entity("PMS.PatientAPI.Models.Patient_Diagnosis_MedicationModel", b =>
                {
                    b.HasOne("PMS.PatientAPI.Models.PatientVisitVitalsModel", "PatientVisitVitalsModel")
                        .WithMany()
                        .HasForeignKey("VisitId");

                    b.Navigation("PatientVisitVitalsModel");
                });
#pragma warning restore 612, 618
        }
    }
}
